#version: "3.8"
services:
  api:
    build: ./api
    container_name: api_cpp_sudoku
    ports:
      - "5000:5000"

  frontend:
    build: ./web
    container_name: frontend_sudoku
    ports:
      - "5173:80"
    depends_on:
      - api
      - backend

  backend:
    build: ./web/server
    container_name: backend_sudoku
